# Generated by Django 3.1.2 on 2021-05-23 09:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoint',
            name='post_image',
            field=models.ImageField(blank=True, height_field=400, upload_to=blog.models.save_image, verbose_name='Изображение пункта', width_field=400),
        ),
    ]
